### ISSUE TITLE
dezelfde waarden

### ISSUE THREAD

**Issue by r20222** [YulanStaal3/the-startup-responsive-interactieve-website#5]
https://github.com/YulanStaal3/the-startup-responsive-interactieve-website/blob/9fb633c2153e9695d4f8956d1c08562d6a5181af/style.css#L87-L104

intro2 en middle hebben dezelfde waarden. Je zou code kunnen besparen door ze met een comma van elkaar te scheiden:

```CSS
.intro-2, .middle {
    width: 90%; 
    margin: 80px auto 0 auto; 
    position: relative;
}
```
